version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: nginx

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: api

    db:
        image: postgres
        restart: always
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
